### ISSUE TITLE
Create SharedPreferencesManager class

### ISSUE THREAD

**Issue by Vanethos** [FogosPT/fogosmobile#10]
Create a `SharedPreferencesManager` to manage the [plugin](https://pub.dev/packages/shared_preferences) class in which:
- The `SharedPreferences` objects from the login is called once, at the startup
- All the `save` functions for saving in the shared preferences are concentrated here
- All the `get` functions for getting data in the shared preferences are concentrated here

Replace all the direct calls to the shared preferences with a call to this class. 

Please note that in order to access the local stored `SharedPreferences` object in the class, ideally this class shouldn't have any static methods. This means that:
- All the getters are not `Futures`
- The `SharedPreferencesManager` class needs to be injected (a parameter) of the classes that depend on it.

**Comment by miguelpruivo** [comment]
Done with #23 and waiting for review to land on `master`.
