### ISSUE TITLE
Add MODIS / VIIRS hotspots to map

### ISSUE THREAD

**Issue by tomahock** [FogosPT/fogosmobile#111]
Examples: 
VIIRS: https://pastebin.com/N6VCN9F1
MODIS: https://pastebin.com/atu4gA4Y

**Comment by tomahock** [comment]
Updated with example responses

**Comment by Vanethos** [comment]
Is there an example on the website that we can see?

**Comment by tomahock** [comment]
<img width="616" alt="Screenshot 2020-08-11 at 10 30 54" src="https://user-images.githubusercontent.com/794581/89881762-d52cb400-dbbd-11ea-961f-b4a327db10b0.png">

When selecting MODIS ou VIIRS put the points on the map. On click show date and confidence

**Comment by goncalo-palma-3r** [comment]
Is it possible to provide the new pin image?

**Comment by Vanethos** [comment]
Endpoints: 
https://fogos.pt/v1/modis

https://fogos.pt/v1/viirs

**Comment by Vanethos** [comment]
Closed via #132
