### ISSUE TITLE
Improve fire resources graph labels

### ISSUE THREAD

**Issue by tomahock** [FogosPT/fogosmobile#113]
![Screenshot_20200602-112844](https://user-images.githubusercontent.com/794581/83510154-70b9ee00-a4c4-11ea-8b5d-b78012741fb4.jpg)

**Comment by Vanethos** [comment]
@tomahock What is intended here?

**Comment by tomahock** [comment]
> @tomahock What is intended here?

Show the hour and not only the minutes. If possible when there is a large amount of data not show every label, but 15 in 15 minutes

**Comment by jcalado** [comment]
Something like this?

![Screenshot_1626594098](https://user-images.githubusercontent.com/26873/126059699-019476e1-f864-41a3-bebf-16f4e8c66c01.png)
