### ISSUE TITLE
Warnings per village

### ISSUE THREAD

**Issue by maverick74** [FogosPT/fogosmobile#121]
Would be great to have  warnings per village instead of having only warnigs per county.

Any plans to introduce this soon?

**Comment by tomahock** [comment]
This is not possible :( 

The village don't came from a table or something that is normalized. Sometime it's written in some form sometimes in other form. So it's not possible to create a channel to subscribe all fires in that village :(

**Comment by maverick74** [comment]
That's weird!

So we can say we want to be warn about any fires that came up in any village that compose the county of Leiria, but it's not possible to say that, instead, we just want to be warned of fires that came up in thevillage of Fatima, for example?

Is that a limitation from the App, from ProCiv service or from other origin?
