### ISSUE TITLE
Table view

### ISSUE THREAD

**Issue by tomahock** [FogosPT/fogosmobile#122]
Create a table view with sort and filters

**Comment by Vanethos** [comment]
Is there design for this feature?

Where can we access this table?

**Comment by Vanethos** [comment]
We can reuse the design in:
https://fogos.pt/tabela

<img width="1187" alt="imagem" src="https://user-images.githubusercontent.com/10728633/89293722-487e7500-d656-11ea-9baf-c1dd1290fdd7.png">

**Comment by Vanethos** [comment]
Closed via #129
