### ISSUE TITLE
Update Android settings to match the app colors

### ISSUE THREAD

**Issue by guivazcabral** [FogosPT/fogosmobile#13]
On Android's app switcher, the header color is not set up correctly.

I think it should be black, since the logo is red.

![Screenshot_20190506-150423](https://user-images.githubusercontent.com/5154363/57243978-4d0d4580-702f-11e9-9f27-40b2e5311856.jpg)

**Comment by miguelpruivo** [comment]
@guivazcabral what's the version affected by this issue? The latest master version actually displays (on both api 27 and 28) the theming color (red) in the app switcher.

**Comment by guivazcabral** [comment]
This happens on the current version that is on the alpha release channel (v 3.0.3) which is up to date with the code that is on the `master` branch

**Comment by miguelpruivo** [comment]
@guivazcabral sorry, I was actually referring to the Android version. Which device / api is this screenshot from?

**Comment by Vanethos** [comment]
@miguelpruivo I assume from the notification bar icon that we are talking about Oreo

**Comment by guivazcabral** [comment]
right, Oreo 8.1 @miguelpruivo
