### ISSUE TITLE
[Urgent] Change map package

### ISSUE THREAD

**Issue by tomahock** [FogosPT/fogosmobile#140]
Change map package to use https://pub.dev/packages/mapbox_gl

Use mapbox styles url: `mapbox://styles/fogospt/cjgppvcdp00aa2spjclz9sjst`

Build an android version for test and send it to me :) 

Then change the mapbox token to `pk.eyJ1IjoiZm9nb3NwdCIsImEiOiJja29hNmkwYTIxdzdzMnhteTltZDE0eHJxIn0.LTBV53JoTn5wGFYq3QFqYg` make another android build and send me the .apk

**Comment by OldMetalmind** [comment]
With the latest PR https://github.com/FogosPT/fogosmobile/pull/145

This issue can be closed.
