### ISSUE TITLE
Add fire details

### ISSUE THREAD

**Issue by guivazcabral** [FogosPT/fogosmobile#2]
We need to add fire stats like we have on the web app. Initially we thought of having a "more info button" on the fire bottom sheet that could lead us to a different screen where we should show:
- the timeline
- the graph with the number of means
- risk of fire

![image](https://user-images.githubusercontent.com/5154363/56810362-0bf68380-682e-11e9-8653-00ec4c96de7e.png)

**Comment by Vanethos** [comment]
Could we ask for a zip file with the assets for this screen?

If not possible, I'll try to download them from the webpage and add the zip file here.

As a suggestion, here is a flutter lib for adding charts in flutter:

https://pub.dartlang.org/packages/charts_flutter

**Comment by tomahock** [comment]
All images used by the website site are in this archive.

For reference all of this could be found [here](https://github.com/FogosPT/fogospt/tree/master/fogospt/public/img) 
[assets.tar.gz](https://github.com/FogosPT/fogosmobile/files/3138200/ass
ets.tar.gz)

**Comment by tomahock** [comment]
Fire general data:
GET https://api-lb.fogos.pt/fires?id=2019140025248

Fire Status History:
GET https://api-lb.fogos.pt/fires/status?id=2019140025248

Fire Danger:
GET https://api-lb.fogos.pt/fires/danger?id=2019140025248

Fire number stats:
GET https://api-lb.fogos.pt/fires/data?id=2019120008897
