### ISSUE TITLE
Informations page

### ISSUE THREAD

**Issue by tomahock** [FogosPT/fogosmobile#29]
https://fogos.pt/informacoes

**Comment by miguelfmp** [comment]
For this issue the only thing missing is an EN version of it, if that is not an issue for now this can be marked as closed

**Comment by Vanethos** [comment]
@miguelfmp how is the status of the issue? Is the translation the only thing missing? Has this been completed in a PR?

**Comment by miguelfmp** [comment]
@Vanethos sorry for the late response, yes the translation is the only thing missing, besides that this was completed on PT #39

**Comment by Vanethos** [comment]
If you can, in the next PRs reference the issue number, so that we can know which PR affected which issue!

I'm closing now this issue and adding a new one for translations
