### ISSUE TITLE
Update marker's icons

### ISSUE THREAD

**Issue by guivazcabral** [FogosPT/fogosmobile#3]
Update marker's icons according to what's used on the web app

**Comment by Vanethos** [comment]
Do we have the assets for this pin? 

And for reference, you are talking about this one, correct?

<img width="66" alt="imagem" src="https://user-images.githubusercontent.com/10728633/57060020-12667e80-6cb8-11e9-9255-ba2174e3e740.png">

**Comment by Vanethos** [comment]
The assets icons are linked here: https://github.com/FogosPT/fogosmobile/issues/2#issuecomment-488673184

**Comment by Vanethos** [comment]
Currently working on this
