### ISSUE TITLE
Stats Page

### ISSUE THREAD

**Issue by tomahock** [FogosPT/fogosmobile#33]
https://fogos.pt/estatisticas

**Comment by Vanethos** [comment]
@tomahock is there any information about the endpoints used in this page?

And as for the map: is it necessary to be like that? Because I don't think that at the moment with the MapBox plugin we can achieve that design in mobile.

**Comment by tomahock** [comment]
We have endpoints!

https://api-lb.fogos.pt/v1/stats/week
https://api-lb.fogos.pt/v1/stats/8hours
https://api-lb.fogos.pt/v1/stats/8hours/yesterday
https://api-lb.fogos.pt/v1/stats/last-night
https://api-lb.fogos.pt/v1/now
https://api-lb.fogos.pt/v1/now/data

We can discard the map for now.
