### ISSUE TITLE
Filter fires by status

### ISSUE THREAD

**Issue by tomahock** [FogosPT/fogosmobile#34]

**Comment by Vanethos** [comment]
@tomahock Can you provide more information about the issue?

- Is there an API for that or you want us to filter locally?
- Where should be the filter for the Fire Status?
- Do you want icons on the list or can it be like the counties list - just text?
- What message should appear to the users if when filtering there are no fires to be displayed?

**Comment by tomahock** [comment]
> Is there an API for that or you want us to filter locally?

Locally

> Where should be the filter for the Fire Status?
Maybe a cog next to the refresh icon that show some filter options.

> Do you want icons on the list or can it be like the counties list - just text?
Text will be fine

> What message should appear to the users if when filtering there are no fires to be displayed?
Just not showing nothing on map

**Comment by miguelpruivo** [comment]
I can take on this one, since all the other available issues are already taken at the moment. 🎉

**Comment by miguelpruivo** [comment]
Can I safely assume that the only possible states are the following?
 - Ocorrência Significativa
 - Vigilância
 - Despacho de 1º Alerta
 - Chegada ao TO
 - Em curso
 - Em resolução
 - Conclusão
 - Encerrada
