### ISSUE TITLE
Add Translations for EN in Informations Page

### ISSUE THREAD

**Issue by Vanethos** [FogosPT/fogosmobile#48]
For the link https://fogos.pt/informacoes We need the translations for EN and then add them to the app.

See PR #39 for more info on the newly added screen.

@tomahock @guivazcabral is there currently a translation for the informations page in En?

**Comment by guivazcabral** [comment]
there is not. once i get the time i'll translate those and send you

**Comment by guivazcabral** [comment]
@Vanethos can you please check if there are any other messages that need translating to English throughout the app? I might as well translate those when I take care of the Informations translations

**Comment by Vanethos** [comment]
During the morning I will check with the repo

**Comment by Vanethos** [comment]
In `main.dart`:
1. Avisos
2. Informações
3. Notificações
4. Parcerias

In `notifications.dart`
1. Concelho

In `info_page.dart`
1. ESTADOS DAS OCORRÊNCIAS
2. Despacho de 1º alerta – Meios em trânsito para o teatro de operações.
3. Chegada ao TO – chegada ao teatro de operações.
4. Em curso - Incêndio em evolução sem limitação de área
5. Em resolução – Incêndio sem perigo de propagação para além do perímetro já atingido
6. Em conclusão – Incêndio extinto, com pequenos focos de combustão dentro do perímetro do incêndio
7. Vigilância – Meios no local para actuar em caso de necessidade
8. Encerrada – Entrada, nas respectivas entidades, de todos os meios envolvidos
9. Falso alarme
10. Falso alerta

I think that's them all

If you translate them I'll add them to the app

**Comment by guivazcabral** [comment]
Avisos
Warnings

Informações
Informations

Notificações
notifications

Parcerias
Partnerships 

Concelho
County

ESTADOS DAS OCORRÊNCIAS
INCIDENT STATUS

Despacho de 1º alerta – Meios em trânsito para o teatro de operações.
First alert dispatch - Resources are moving to incident location

Chegada ao TO – chegada ao teatro de operações.
Arrival to Incident Scene - Resources arrived at incidient location.

Em curso - Incêndio em evolução sem limitação de área
Ongoing - Fire is ongoing without boundaries

Em resolução – Incêndio sem perigo de propagação para além do perímetro já atingido
Settling - Fire without risk of propagation beyond boundaries

Em conclusão – Incêndio extinto, com pequenos focos de combustão dentro do perímetro do incêndio
Closing - Fire is extinguished, while there could be still some fire spots within incident boundaries

Vigilância – Meios no local para actuar em caso de necessidade
Supervision - Resources at incident location to act if needed

Encerrada – Entrada, nas respectivas entidades, de todos os meios envolvidos
Closed - All resources are back at their headquarters.

Falso alarme
False alarm

Falso alerta
False alarm

**Comment by Vanethos** [comment]
will work on this today
