### ISSUE TITLE
Change 'means' to  'resources'

### ISSUE THREAD

**Issue by tomahock** [FogosPT/fogosmobile#52]
![image](https://user-images.githubusercontent.com/794581/58237823-f5185380-7d3d-11e9-8531-fcab0570ead1.png)

**Comment by Vanethos** [comment]
Can be done with Issue #48

**Comment by Zzay7** [comment]
Sugiro que se mude para
Firemen 
Vehicles 
Aerial not aereal

**Comment by Vanethos** [comment]
@tomahock @guivazcabral do you agree?

**Comment by guivazcabral** [comment]
sounds good!
