### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by miguelpruivo** [FogosPT/fogosmobile#60]
Currently the project is unlicensed. Even though this is a community project, I would suggest have it attached to a permissive license, by creating a LICENSE file.

Some good permissive licenses that can fit this project would be from [Apache 2.0](https://choosealicense.com/licenses/apache-2.0/), [MIT](https://choosealicense.com/licenses/mit/) or even [The Unlicense](https://choosealicense.com/licenses/unlicense/).

Maybe @tomahock and/or @guivazcabral can (should) give an opinion on this.

**Comment by guivazcabral** [comment]
There's a license statement in readme.md file.

**Comment by miguelpruivo** [comment]
@guivazcabral my bad. I was looking for a LICENSE file and couldn't find one. Anyway, probably wouldn't be a bad idea to move it for one.
