### ISSUE TITLE
Add List page 

### ISSUE THREAD

**Issue by tomahock** [FogosPT/fogosmobile#62]
https://fogos.pt/lista

**Comment by Vanethos** [comment]
To show the static map, we can use the coordinates from the fire and use mapbox's static maps api

The result will be an URL like the following:

https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v11/static/-7.522403,37.219971,15,0,00/450x300?access_token=XXX

https://docs.mapbox.com/help/how-mapbox-works/static-maps/
