### ISSUE TITLE
Save map filter options across sessions

### ISSUE THREAD

**Issue by tomahock** [FogosPT/fogosmobile#63]

**Comment by Vanethos** [comment]
The map filters could be saved in the [shared_preferences](https://pub.dev/packages/shared_preferences) as an array of id's.

**Comment by 0rp3u** [comment]
I don't mind doing this, but if anyone is interested in this for their first contribution i will gladly leave it for them.

**Comment by miguelpruivo** [comment]
Somehow, it looks like this is not working and the filters are not being kept across sessions in the version that is currently available on the AppStore.

CC: @Orp3u

**Comment by 0rp3u** [comment]
Tested it on the dev and master branch and it's working, are you sure the uploaded apk had the right code?

**Comment by miguelpruivo** [comment]
I believe so. But @guivazcabral may know.

**Comment by guivazcabral** [comment]
Production doesn't have the most recent code, but I don't think the newest code has changes regarding filters. I'll give it a look when I can. Thanks guys

**Comment by guivazcabral** [comment]
Closing this since this seems to be fixed on the version available at the stores
