### ISSUE TITLE
Add Fire Risk information

### ISSUE THREAD

**Issue by tomahock** [FogosPT/fogosmobile#65]
Not sure how can I pass this tou you.

On frontend we are using this:

https://api-lb.fogos.pt/v1/risk-today
https://api-lb.fogos.pt/v1/risk-tomorrow
https://api-lb.fogos.pt/v1/risk-after

**Comment by Vanethos** [comment]
The objective is to make a grid-like map with the risk assessment for each area of the country, such as:

![imagem](https://user-images.githubusercontent.com/10728633/58464394-e531b280-8135-11e9-96bb-93d76ea7c04d.png)

We must check if we can use the response that @tomahock gave in the OP, and if we can add this to the layer of tiles in the flutter_map plugin.

This needs to be researched and discussed here before proceeding to implement.

**Comment by guivazcabral** [comment]
AFAIK, flutter_map plugin doesn't support (yet) polygons

**Comment by Vanethos** [comment]
@guivazcabral Polygon layer is supported for Flutter Map: https://github.com/johnpryan/flutter_map/blob/master/lib/src/layer/polygon_layer.dart

We should see how this works and if this is an optimal solution for us for the current backend response for the polygons

**Comment by tomahock** [comment]
Bumping this issue as top priority

**Comment by miguelpruivo** [comment]
@tomahock I need details on how to interpret the API data and its properties meanings. I'm used to see polygons with multiple coordinates for each polygon, but this seems to bit a different with only on coordinate per entry.

**Comment by tomahock** [comment]
bumping this issue.

@miguelpruivo can we talk on slack?

**Comment by tomahock** [comment]
Waiting for https://github.com/FogosPT/fogosapi/pull/19

Endpoints:

v2/rcm/today
v2/rcm/tomorrow
v2/rcm/after
