### ISSUE TITLE
Add Warnings Page for Madeira

### ISSUE THREAD

**Issue by tomahock** [FogosPT/fogosmobile#66]
https://api-lb.fogos.pt/v1/madeira/warnings

https://fogos.pt/madeira/avisos

**Comment by Vanethos** [comment]
The design could be the same as we see in the Warnings page, with the new endpoint that's described in this post.

@tomahock do you confirm that the response is the same for Madeira and for the general warnings?

**Comment by tomahock** [comment]
Yes! It's the same schema!
