### ISSUE TITLE
Translations on information page

### ISSUE THREAD

**Issue by guivazcabral** [FogosPT/fogosmobile#72]
English translations are needed on the resources and fire risk sections of the info page.

I'll leave the translations here once I get the time to get those done.

![AEE72E43-4198-494C-9C33-9E53A9270F66](https://user-images.githubusercontent.com/5154363/58578878-bf91cf80-8241-11e9-8d4c-1bb1b0012985.png)

**Comment by Vanethos** [comment]
Sorry about this @guivazcabral missed this one.

I assumed this was from an API call.

Waiting for the translations to put them in the project
