### ISSUE TITLE
Handle important events

### ISSUE THREAD

**Issue by tomahock** [FogosPT/fogosmobile#77]
Missing icon and aditional information

![image](https://user-images.githubusercontent.com/794581/58788355-a7280900-85e3-11e9-813e-6557700b6dea.png)

Check this https://api-lb.fogos.pt/fires?id=2019040016187

`important:true`
`cos`
`pco`
`POSITDescricao`
`PontoSituacao`
`Notas`

All of this properties can exist or not

**Comment by Vanethos** [comment]
@tomahock 

What icon should we use for each new label?

If I'm understanding correctly, we also need to update the info for the fire, correct?

**Comment by tomahock** [comment]
@Vanethos 

The icon in web is with the color `#ff410c` and it's the same icon.

That properties should be in the first fire details screen

**Comment by Vanethos** [comment]
@tomahock so that we're clear

you're saying that this is missing?

<img width="54" alt="imagem" src="https://user-images.githubusercontent.com/10728633/58789330-caec4e80-85e5-11e9-8a66-0b7fd4488c96.png">

**Comment by tomahock** [comment]
The `statusCode` on this case should be 99
But they remove this example as important and statusCode reseted to 5 at this moment.

So i guess that the icon was really missing :)

**Comment by Vanethos** [comment]
@tomahock one thing that I'm seeing.

The fires have a property that comes from the backend which is `statusColor`, and with this we define the color of the map pin:

`'0xFF$fireStatus'`

If this is the case for all the fires, why isn't it the case for the important fires such as we have seen now?
